//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabaKirala
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sofor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Ehliyet { get; set; }
        public System.DateTime Yas { get; set; }
        public int AracId { get; set; }
    }
}
